version: 0.2
phases: 
  install: 
    runtime-versions: 
        java: openjdk11
  build: 
    commands:  
      - mvn package
      - aws cloudformation package --template-file sam.yaml --s3-bucket sample-cicd-spring --output-template-file outputSamTemplate.yaml
artifacts:
  type: zip
  files:
    - sam.yaml
    - outputSamTemplate.yaml
    - target/microservice.jar
    
    
    
# version: 0.2

# phases:
#   build:
#     commands:
#       - echo Build started on `date`
#       - mvn test
#   post_build:
#     commands:
#       - echo Build completed on `date`
#       - mvn package
# artifacts:
#   files:
#     - zalando-boot-etcd/target/zalando-boot-etcd-2.4-SNAPSHOT.jar    
